import { test, expect, beforeAll, afterAll } from 'bun:test';
import { mkdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import type { Subprocess } from 'bun';
import Database from 'bun:sqlite';

const TEST_DIR = './test-e2e-full-workflow';
let originalCwd: string;
let supervisorProc: Subprocess | null = null;

beforeAll(async () => {
  originalCwd = process.cwd();

  // Clean and create test directory
  if (existsSync(TEST_DIR)) {
    await rm(TEST_DIR, { recursive: true, force: true });
  }
  await mkdir(TEST_DIR, { recursive: true });
  process.chdir(TEST_DIR);

  // Initialize git repo (required by init)
  await Bun.spawn(['git', 'init'], { stdout: 'inherit' }).exited;
  await Bun.spawn(['git', 'config', 'user.email', 'test@example.com'], { stdout: 'inherit' }).exited;
  await Bun.spawn(['git', 'config', 'user.name', 'Test User'], { stdout: 'inherit' }).exited;
});

afterAll(async () => {
  // Kill supervisor if running
  if (supervisorProc && supervisorProc.exitCode === null) {
    supervisorProc.kill();
    await supervisorProc.exited;
  }

  // Cleanup
  process.chdir(originalCwd);
  if (existsSync(TEST_DIR)) {
    await rm(TEST_DIR, { recursive: true, force: true });
  }
});

test('Full workflow: init → mock start → status → stop', async () => {
  // Step 1: Run init
  console.log('Step 1: Running init...');
  const initProc = Bun.spawn([
    'bun',
    `${originalCwd}/src/cli.ts`,
    'init'
  ], {
    stdout: 'pipe',
    stderr: 'pipe',
  });

  await initProc.exited;
  expect(initProc.exitCode).toBe(0);

  // Verify files created
  expect(existsSync('.takopi-smithers/config.toml')).toBe(true);
  expect(existsSync('.smithers/workflow.tsx')).toBe(true);
  expect(existsSync('TAKOPI_SMITHERS.md')).toBe(true);
  expect(existsSync('CLAUDE.md')).toBe(true);
  expect(existsSync('AGENTS.md')).toBe(true);

  console.log('✅ Init completed successfully');

  // Step 2: Keep the default workflow generated by init
  // The default workflow from init is already minimal and suitable for testing
  console.log('Step 2: Using default workflow from init...');
  console.log('✅ Workflow ready');

  // Step 3: Run doctor to validate setup
  console.log('Step 3: Running doctor checks...');
  const doctorProc = Bun.spawn([
    'bun',
    `${originalCwd}/src/cli.ts`,
    'doctor'
  ], {
    stdout: 'pipe',
    stderr: 'pipe',
  });

  await doctorProc.exited;
  // Doctor might fail on missing Takopi, but should still run
  console.log('✅ Doctor checks completed');

  // Step 4: Start supervisor in dry-run mode (skip Takopi)
  console.log('Step 4: Starting supervisor in dry-run mode...');
  supervisorProc = Bun.spawn([
    'bun',
    `${originalCwd}/src/cli.ts`,
    'start',
    '--dry-run'
  ], {
    stdout: 'pipe',
    stderr: 'pipe',
  });

  // Wait for supervisor to initialize and workflow to start
  await new Promise(resolve => setTimeout(resolve, 5000));

  // Check if it's still running or if it completed
  const stillRunning = supervisorProc.exitCode === null;
  console.log(`Supervisor state: ${stillRunning ? 'running' : 'exited with code ' + supervisorProc.exitCode}`);

  // It's ok if the workflow completes quickly - just verify it started
  console.log('✅ Supervisor processed workflow');

  // Step 5: Check status while running
  console.log('Step 5: Checking status...');
  const statusProc = Bun.spawn([
    'bun',
    `${originalCwd}/src/cli.ts`,
    'status',
    '--json'
  ], {
    stdout: 'pipe',
    stderr: 'pipe',
  });

  await statusProc.exited;
  const statusOutput = await new Response(statusProc.stdout).text();
  console.log('Status output:', statusOutput);

  const status = JSON.parse(statusOutput);
  expect(status.status).toBeDefined();
  expect(status.heartbeat).toBeDefined();
  console.log('✅ Status check passed');

  // Step 6: Verify DB exists and has state table
  console.log('Step 6: Verifying DB state...');
  if (existsSync('.smithers/workflow.db')) {
    const db = new Database('.smithers/workflow.db', { readonly: true });

    // Check if state table exists
    const tables = db.query("SELECT name FROM sqlite_master WHERE type='table' AND name='state'").all();

    if (tables.length > 0) {
      const heartbeatRow = db.query('SELECT value FROM state WHERE key = "supervisor.heartbeat"').get() as { value: string } | null;
      const statusRow = db.query('SELECT value FROM state WHERE key = "supervisor.status"').get() as { value: string } | null;
      expect(heartbeatRow || statusRow).toBeDefined();
      console.log('✅ DB state verified');
    } else {
      console.log('⚠️  State table not yet created (workflow may not have started)');
    }

    db.close();
  } else {
    console.log('⚠️  Workflow DB not yet created');
  }

  // Step 7: Stop supervisor
  console.log('Step 7: Stopping supervisor...');
  const stopProc = Bun.spawn([
    'bun',
    `${originalCwd}/src/cli.ts`,
    'stop'
  ], {
    stdout: 'pipe',
    stderr: 'pipe',
  });

  await stopProc.exited;
  expect(stopProc.exitCode).toBe(0);

  // Wait for processes to terminate
  await new Promise(resolve => setTimeout(resolve, 2000));
  console.log('✅ Supervisor stopped');

  console.log('\n🎉 Full workflow test completed successfully!');
}, 60000); // 60 second timeout

test('Workflow file-watch detects changes', async () => {
  // This test validates Milestone 3: file-watch reload
  // Start supervisor, modify workflow file, verify supervisor detects the change

  // Step 1: Start supervisor with minimal workflow
  const startTime = Date.now();
  supervisorProc = Bun.spawn([
    'bun',
    `${originalCwd}/src/cli.ts`,
    'start',
    '--dry-run'
  ], {
    stdout: 'pipe',
    stderr: 'pipe',
  });

  await new Promise(resolve => setTimeout(resolve, 3000));

  // Step 2: Get initial heartbeat
  let initialHeartbeat: string | null = null;
  if (existsSync('.smithers/workflow.db')) {
    const db = new Database('.smithers/workflow.db', { readonly: true });
    const tables = db.query("SELECT name FROM sqlite_master WHERE type='table' AND name='state'").all();
    if (tables.length > 0) {
      const row = db.query('SELECT value FROM state WHERE key = "supervisor.heartbeat"').get() as { value: string } | null;
      initialHeartbeat = row?.value || null;
    }
    db.close();
  }

  // Step 3: Modify workflow file
  const currentWorkflow = await Bun.file('.smithers/workflow.tsx').text();
  const timestamp = Date.now();
  const modifiedWorkflow = currentWorkflow.replace(
    'name="example-workflow"',
    `name="example-workflow-${timestamp}"`
  );
  await Bun.write('.smithers/workflow.tsx', modifiedWorkflow);
  console.log('Modified workflow file at', new Date().toISOString());

  // Step 4: Wait for file-watch debounce + restart (file watcher has 2s debounce)
  await new Promise(resolve => setTimeout(resolve, 4000));

  // Step 5: Verify heartbeat was updated (indicates workflow restarted)
  if (existsSync('.smithers/workflow.db')) {
    const db = new Database('.smithers/workflow.db', { readonly: true });
    const row = db.query('SELECT value FROM state WHERE key = "supervisor.heartbeat"').get() as { value: string } | null;
    const newHeartbeat = row?.value || null;
    db.close();

    // Heartbeat should be updated after the file change
    if (initialHeartbeat && newHeartbeat) {
      const initialTime = new Date(initialHeartbeat).getTime();
      const newTime = new Date(newHeartbeat).getTime();
      expect(newTime).toBeGreaterThan(initialTime);
      console.log('✅ Heartbeat updated after file change');
    } else {
      console.log('⚠️  Could not verify heartbeat update (workflow may have completed)');
    }
  }

  // Cleanup
  if (supervisorProc && supervisorProc.exitCode === null) {
    supervisorProc.kill();
    await supervisorProc.exited;
  }
  supervisorProc = null;

  console.log('✅ File-watch test passed');
}, 30000);
